# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: gm
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  # windows and linux use upx compression
  - id: gm1
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    ldflags:
     - -s -w -X main.version={{.Version}}
    hooks:
      post:
       - upx "{{ .Path }}"
  # mac builds on github has problems with upx compression
  - id: gm2
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    ldflags:
     - -s -w -X main.version={{.Version}}
archives:
  - replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      386: 32bit
      amd64: 64bit
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
