# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: gm
env:
  - GOLDMARK_VERSION={{ if index .Env "GOLDMARK_VERSION" }}{{ .Env.GOLDMARK_VERSION }}{{ else }}--{{ end }}
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
     - "-s -w -X 'main.version={{ .Version }}' -X 'main.goldmarkVersion={{ .Env.GOLDMARK_VERSION }}'"
archives:
  - 
    # DEPRECATED: `archives.replacements` should not be used anymore, check https://goreleaser.com/deprecations#archivesreplacements for more info
    # - replacements:
    #     darwin: MacOS
    #     linux: Linux
    #     windows: Windows
    #     386: 32bit
    #     amd64: 64bit
    # We replace this with the following:
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}MacOS
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "windows" }}Windows
      {{- else }}{{ .Os }}
      {{- end }}_
      {{- if eq .Arch "amd64" }}64bit
      {{- else if eq .Arch "386" }}32bit
      {{- else }}{{ .Arch }}
      {{- end }}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
